# coding: utf-8

"""
    TickTick API

    [TickTick](https://ticktick.com/) TODO task manager.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from pyticktick.openapi_client.models.open_v1_project_project_id_post_request import OpenV1ProjectProjectIdPostRequest  # noqa: E501

class TestOpenV1ProjectProjectIdPostRequest(unittest.TestCase):
    """OpenV1ProjectProjectIdPostRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OpenV1ProjectProjectIdPostRequest:
        """Test OpenV1ProjectProjectIdPostRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OpenV1ProjectProjectIdPostRequest`
        """
        model = OpenV1ProjectProjectIdPostRequest()  # noqa: E501
        if include_optional:
            return OpenV1ProjectProjectIdPostRequest(
                id = '',
                name = '',
                color = '',
                sort_order = 56,
                view_mode = 'list',
                kind = 'TASK',
                closed = True,
                group_id = '',
                permission = '',
                project_id = ''
            )
        else:
            return OpenV1ProjectProjectIdPostRequest(
                name = '',
        )
        """

    def testOpenV1ProjectProjectIdPostRequest(self):
        """Test OpenV1ProjectProjectIdPostRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
