# coding: utf-8

# flake8: noqa

"""
    TickTick API

    [TickTick](https://ticktick.com/) TODO task manager.

    The version of the OpenAPI document: 0.0.1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# Define package exports
__all__ = [
    "DefaultApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "ChecklistItem",
    "Column",
    "OauthTokenPost200Response",
    "OauthTokenPostRequest",
    "OpenV1ProjectProjectIdPostRequest",
    "OpenV1ProjectProjectIdTaskTaskIdCompletePostRequest",
    "OpenV1TaskTaskIdPostRequest",
    "Project",
    "ProjectData",
    "Status",
    "Task",
]

# import apis into sdk package
from pyticktick.api.default_api import DefaultApi as DefaultApi

# import ApiClient
from pyticktick.api_response import ApiResponse as ApiResponse
from pyticktick.api_client import ApiClient as ApiClient
from pyticktick.configuration import Configuration as Configuration
from pyticktick.exceptions import OpenApiException as OpenApiException
from pyticktick.exceptions import ApiTypeError as ApiTypeError
from pyticktick.exceptions import ApiValueError as ApiValueError
from pyticktick.exceptions import ApiKeyError as ApiKeyError
from pyticktick.exceptions import ApiAttributeError as ApiAttributeError
from pyticktick.exceptions import ApiException as ApiException

# import models into sdk package
from pyticktick.models.checklist_item import ChecklistItem as ChecklistItem
from pyticktick.models.column import Column as Column
from pyticktick.models.oauth_token_post200_response import OauthTokenPost200Response as OauthTokenPost200Response
from pyticktick.models.oauth_token_post_request import OauthTokenPostRequest as OauthTokenPostRequest
from pyticktick.models.open_v1_project_project_id_post_request import OpenV1ProjectProjectIdPostRequest as OpenV1ProjectProjectIdPostRequest
from pyticktick.models.open_v1_project_project_id_task_task_id_complete_post_request import OpenV1ProjectProjectIdTaskTaskIdCompletePostRequest as OpenV1ProjectProjectIdTaskTaskIdCompletePostRequest
from pyticktick.models.open_v1_task_task_id_post_request import OpenV1TaskTaskIdPostRequest as OpenV1TaskTaskIdPostRequest
from pyticktick.models.project import Project as Project
from pyticktick.models.project_data import ProjectData as ProjectData
from pyticktick.models.status import Status as Status
from pyticktick.models.task import Task as Task
